-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public."Aluno" CASCADE;
CREATE TABLE public."Aluno"
(
    nome VARCHAR(15) NOT NULL,
    nome_completo VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    matricula VARCHAR(12) NOT NULL,
    curso VARCHAR(50) NOT NULL,
    ano_entrada VARCHAR(4) NOT NULL,
    id_topic VARCHAR(100) NOT NULL UNIQUE,
    id_msg VARCHAR(100) NOT NULL UNIQUE,
    carga_horaria_opt VARCHAR(4) NOT NULL,
    carga_horaria_compl VARCHAR(4) NOT NULL,
    carga_horaria_obrigat VARCHAR(4) NOT NULL,
    carga_horaria_total VARCHAR(4) NOT NULL,
    percent_concluido VARCHAR(7) NOT NULL,
    coeficiente VARCHAR(7) NOT NULL,
    senha VARCHAR(100) NOT NULL, 
    PRIMARY KEY (matricula)
);

DROP TABLE IF EXISTS public."Atividades";
CREATE TABLE public."Atividades"
(
    id_atividade VARCHAR(100) NOT NULL,
    nome_disciplina VARCHAR(100) NOT NULL,
    nome_atividade VARCHAR(200) NOT NULL,
    data VARCHAR(10) NOT NULL,
    id_matricula VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_atividade)
);

DROP TABLE IF EXISTS public."Mensagem";
CREATE TABLE public."Mensagem"
(
    id VARCHAR(100)  NOT NULL,
    nome_autor VARCHAR(100) NOT NULL,
    conteudo VARCHAR(200) NOT NULL,
    data VARCHAR(10) NOT NULL,
    id_topic VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Topico";
CREATE TABLE public."Topico"
(
    id_topic VARCHAR(100) NOT NULL,
    mensagem VARCHAR(200) NOT NULL,
    categoria_topic VARCHAR(100) NOT NULL,
    nome_topic VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_topic)
);

ALTER TABLE public."Mensagem"
    ADD FOREIGN KEY (id)
    REFERENCES public."Aluno" (id_msg)
    NOT VALID;


ALTER TABLE public."Topico"
    ADD FOREIGN KEY (id_topic)
    REFERENCES public."Aluno" (id_topic)
    NOT VALID;


ALTER TABLE public."Atividades"
    ADD FOREIGN KEY (id_matricula)
    REFERENCES public."Aluno" (matricula)
    NOT VALID;


ALTER TABLE public."Mensagem"
    ADD FOREIGN KEY (id_topic)
    REFERENCES public."Topico" (id_topic)
    NOT VALID;

END;